language: ruby
cache:
    - bundler
before_install:
    - gem update --system
    - gem install bundler
deploy:
    provider: heroku
    api_key:
        secure: KEY
    app: ionicsoft-vidon
    on:
        repo: ionicsoft/vidon
